mrshll_scraper:
    resource: "@MrshllScraperBundle/Resources/config/routing.yml"
    prefix:   /scraper

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mrshll_site:
    resource: "@MrshllSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
