council_list:
  path: /
  defaults: { _controller: MrshllSiteBundle:Default:viewCouncils }


council_north:
  path: /northumberland
  defaults: { _controller: MrshllSiteBundle:Default:viewNorthumbria }

council_ncl:
  path: /newcastle
  defaults: { _controller:MrshllSiteBundle:Default:viewNewcastle }

council_create:
    path: /create
    defaults: { _controller: MrshllSiteBundle:Council:create }
    methods: [POST]

council_delete:
  path: /delete
  defaults: { _controller: MrshllSiteBundle:Council:delete }
  methods: [POST]

council_record_add:
  path: /addrecord
  defaults: { _controller: MrshllSiteBundle:Council:addRecord }
  methods: [POST]

council_record_remove:
  path: /removerecord
  defaults: { _controller: MrshllSiteBundle:Council:removeRecord }
  methods: [POST]

council_record_nuke:
  path: /nukerecords
  defaults: { _controller: MrshllSiteBundle:Council:nukeRecords }
  methods: [POST]
