council_list:
  path: /
  defaults: { _controller: MrshllSiteBundle:Default:viewCouncils }


council_page:
  path: /view/{id}
  defaults: { _controller: MrshllSiteBundle:Default:viewCouncilPage }

council_create:
    path: /create
    defaults: { _controller: MrshllSiteBundle:Council:create }
    methods: [POST]

council_delete:
  path: /delete
  defaults: { _controller: MrshllSiteBundle:Council:delete }
  methods: [POST]
