mrshll_homepage:
    path:     /
    defaults: { _controller: MrshllSiteBundle:Default:index }


mrshll_testpage:
    path: /test
    defaults: { _controller: MrshllSiteBundle:Default:test }

council_routes:
    resource: "@MrshllSiteBundle/Resources/config/councilRoutes.yml"
    prefix: /council

scraper_routes:
    resource: "@MrshllSiteBundle/Resources/config/scraperRoutes.yml"
    prefix: /scraper
