mrshll_homepage:
    path:     /
    defaults: { _controller: MrshllSiteBundle:Default:index }

mrshll_orglist:
    path: /org/
    defaults: { _controller: MrshllSiteBundle:Default:org }

mrshll_orgview:
    path: /org/{id}
    defaults: { _controller: MrshllSiteBundle:Default:orgView }

mrshll_mockup:
    path: /org/mockup
    defaults: { _controller: MrshllSiteBundle:Default:mockup }


mrshll_overview:
    path: /overview
    defaults: { _controller: MrshllSiteBundle:Default:overview }
