mrshll_homepage:
    path:     /
    defaults: { _controller: MrshllSiteBundle:Default:index }


mrshll_testpage:
    path: /test
    defaults: { _controller: MrshllSiteBundle:Default:test }

council_routes:
    resource: "@MrshllSiteBundle/Resources/config/councilRoutes.yml"
    prefix: /council

npo_routes:
  resource: "@MrshllSiteBundle/Resources/config/npoRoutes.yml"
  prefix: /npo

record_routes:
    resource: "@MrshllSiteBundle/Resources/config/recordRoutes.yml"
    prefix: /record

scraper_routes:
    resource: "@MrshllSiteBundle/Resources/config/scraperRoutes.yml"
    prefix: /scraper
